name: Docker image CI for GHCR

on:
    push:
        branches: [main]

jobs:
    buildAndPublish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build and push the image
              run: |
                  IMAGE_TAG=${{ github.sha }}
                  cd application
                  docker login --username ${{secrets.USERNAME}} --password ${{secrets.GHCR_PAT}} ghcr.io
                  docker build . \
                    -t ghcr.io/${{ secrets.USERNAME }}/application:${IMAGE_TAG} \
                    -t ghcr.io/${{ secrets.USERNAME }}/application:latest
                  docker push ghcr.io/${{ secrets.USERNAME }}/application:${IMAGE_TAG}
                  docker push ghcr.io/${{ secrets.USERNAME }}/application:latest

            - name: Verify image push
              run: |
                  echo "Image pushed successfully to ghcr.io/${{ secrets.USERNAME }}/application"
